### PR TITLE
fix for #151 plus documentation updates

### PR DESCRIPTION
**Pull request by vojtechhuser**
also per prior request - age rule (warning grade message) added

### CODE REVIEW

**Comment by vojtechhuser** [comment]
@t-abdul-basser  It has been now 2 weeks since my original commit. We have a lot of conditions that will take a long time to satisfy. Perhaps we can make some compromises and proceed with smaller steps. (e.g., ignore the bad join for just a while). (turn of exportToJSON until Chris has time to look into the join).

**Comment by chrisknoll** [comment]
I am hoping to resolve the hangs on the CI server today. Please be patient @vojtechhuser .

**Comment by chrisknoll** [comment]
@vojtechhuser , please merge from latest master on OHDSI/Achilles into your branch and i'll arrange to have this PR pushed into the OHDSI Repo.

**Comment by vojtechhuser** [comment]
Let me simplify the PR list by withdrawing it. (and incorporate it into a December contribution)

**Comment by t-abdul-basser** [comment]
@vojtechhuser Thanks! That makes sense to me. The delay on this PR is regrettable but we needed to straighten out the CI process. Thanks again @chrisknoll @leeevans @msuchard.

**Pull request closed without merging**
