### PR TITLE
New features: shiny app, logging, vignette, verboseMode and bugfixes

### PR DESCRIPTION
**Pull request by alondhe**
Hi @vojtechhuser , @t-abdul-basser,

In preparation for the DQ class during the Symposium in a few days, I worked on some lingering bugs, but also added a bunch of (hopefully) useful features to help new users get accustomed to using Achilles.

If we're lucky, perhaps we can make this release v1.6.3 in time for the DQ class.

**Issues Addressed:**
#326 #325 #317 #324 

**New Features**
- Shiny Application for reviewing Heel results, with drilldown into associated SQL scripts
- Logging using ParallelLogger, which allows for nice viewing of log files
- Vignette for how to use Achilles
- Verbose mode to limit the amount of detail is outputted to the console
- Using invisible() on the return value to prevent a huge text dump from appearing if you don't assign a variable to the function calls

I took all of @pegeler's changes as well, but made a few edits to the DESCRIPTION file.

### CODE REVIEW

**Comment by t-abdul-basser** [comment]
Thank you @alondhe! Releasing again before the tutorial is an excellent idea. I will complete my review of @pegler PR and this by EOB tomorrow and aim to release v1.6.2, by Thursday.

**Comment by alondhe** [comment]
Thanks @t-abdul-basser -- if it's not possible to merge by then, perhaps we can just make a new branch and direct people there during the class.

**Comment by t-abdul-basser** [comment]
OK. Creating a release candidate 1.6.2 branch will be part of the release process.

**Comment by vojtechhuser** [comment]
This is great advance. I also vote for trying to make it prior tutorial. It almost deserves 1.7 or even 2.0

**Comment by t-abdul-basser** [comment]
Resolving conflict and merging.

**Pull request merged**
