### PR TITLE
CAST performance update

### PR DESCRIPTION
**Pull request by chrisknoll**
Change CAST in the ON clause to casting in the subselect of the sqlPrevalenceByGenderAgeYear.sql.  Note the GROUP BY clause is required for PDW environments so that rows with non-varchar values are not casted into ints.

This PR is trying to address the timeout issue identified in #152 and #149 .  This PR does not address all cases where casting concept_id to VARCHAR, but it does address the one specifically identified in #149. I have tested this on our local PDW environment and the case where we get an error casting a varchar into an int even tho the analysis_id is set to a specific non-varchar stratum_1 value is fixed by adding a GROUP BY to the inner sub-query 'num' and 'denom'.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Additional slow queries from @leeevans -

```
select 	concept_hierarchy.concept_id,
	isNull(concept_hierarchy.level3_concept_name,'NA') 
	+ '||' + isNull(concept_hierarchy.level2_concept_name,'NA')
	+ '||' + isNull(concept_hierarchy.level1_concept_name,'NA')
	+ '||' + isNull(concept_hierarchy.concept_name, 'NA') as concept_path,
	ar1.count_value as num_persons, 
	1.0*ar1.count_value / denom.count_value as percent_persons,
	1.0*ar2.count_value / ar1.count_value as records_per_person
from (select * from ohdsi.dbo.ACHILLES_results where analysis_id = 800) ar1
	inner join
	(select * from ohdsi.dbo.ACHILLES_results where analysis_id = 801) ar2
	on ar1.stratum_1 = ar2.stratum_1
	inner join
	(
		select obs.concept_id, obs.concept_name, max(c1.concept_name) as level1_concept_name, max(c2.concept_name) as level2_concept_name, max(c3.concept_name) as level3_concept_name
		from
		(
			select concept_id, concept_name
			from CDMV5.dbo.concept
			where domain_id = 'Observation'
		) obs left join CDMV5.dbo.concept_ancestor ca1 on obs.concept_id = ca1.DESCENDANT_CONCEPT_ID and ca1.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c1 on ca1.ANCESTOR_CONCEPT_ID = c1.concept_id
		left join CDMV5.dbo.concept_ancestor ca2 on c1.concept_id = ca2.DESCENDANT_CONCEPT_ID and ca2.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c2 on ca2.ANCESTOR_CONCEPT_ID = c2.concept_id
		left join CDMV5.dbo.concept_ancestor ca3 on c2.concept_id = ca3.DESCENDANT_CONCEPT_ID and ca3.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c3 on ca3.ANCESTOR_CONCEPT_ID = c3.concept_id
		group by obs.concept_id, obs.concept_name
	) concept_hierarchy on ar1.stratum_1 = CAST(concept_hierarchy.concept_id as VARCHAR),
	(select count_value from ohdsi.dbo.ACHILLES_results where analysis_id = 1) denom
order by ar1.count_value desc

```


---------------------------------------
```
select   concept_hierarchy.concept_id,
  isNull(concept_hierarchy.soc_concept_name,'NA') + '||' + isNull(concept_hierarchy.hlgt_concept_name,'NA') + '||' + isNull(concept_hierarchy.hlt_concept_name,'NA') + '||' + isNull(concept_hierarchy.pt_concept_name,'NA') + '||' + isNull(concept_hierarchy.snomed_concept_name,'NA') concept_path,	ar1.count_value as num_persons, 
	round(1.0*ar1.count_value / denom.count_value,5) as percent_persons,
	round(1.0*ar2.count_value / ar1.count_value,5) as records_per_person
from (select * from ohdsi.dbo.ACHILLES_results where analysis_id = 400) ar1
	inner join
	(select * from ohdsi.dbo.ACHILLES_results where analysis_id = 401) ar2
	on ar1.stratum_1 = ar2.stratum_1
	inner join
	(
		select snomed.concept_id, 
			snomed.concept_name as snomed_concept_name,
			pt_to_hlt.pt_concept_name,
			hlt_to_hlgt.hlt_concept_name,
			hlgt_to_soc.hlgt_concept_name,
			soc.concept_name as soc_concept_name
		from	
		(
			select concept_id, concept_name
			from CDMV5.dbo.concept
			where domain_id = 'Condition'
		) snomed
		left join
			(select c1.concept_id as snomed_concept_id, max(c2.concept_id) as pt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.domain_id = 'Condition'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id
			) snomed_to_pt
		on snomed.concept_id = snomed_to_pt.snomed_concept_id

		left join
			(select c1.concept_id as pt_concept_id, c1.concept_name as pt_concept_name, max(c2.concept_id) as hlt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
		  CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) pt_to_hlt
		on snomed_to_pt.pt_concept_id = pt_to_hlt.pt_concept_id

		left join
			(select c1.concept_id as hlt_concept_id, c1.concept_name as hlt_concept_name, max(c2.concept_id) as hlgt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) hlt_to_hlgt
		on pt_to_hlt.hlt_concept_id = hlt_to_hlgt.hlt_concept_id

		left join
			(select c1.concept_id as hlgt_concept_id, c1.concept_name as hlgt_concept_name, max(c2.concept_id) as soc_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) hlgt_to_soc
		on hlt_to_hlgt.hlgt_concept_id = hlgt_to_soc.hlgt_concept_id

		left join CDMV5.dbo.concept soc
		 on hlgt_to_soc.soc_concept_id = soc.concept_id
	) concept_hierarchy
	on ar1.stratum_1 = CAST(concept_hierarchy.concept_id as VARCHAR)
	,
	(select count_value from ohdsi.dbo.ACHILLES_results where analysis_id = 1) denom

order by ar1.count_value desc

```
---------------------------------------------------------

```
select 	concept_hierarchy.concept_id,
	isNull(concept_hierarchy.soc_concept_name,'NA') + '||' + isNull(concept_hierarchy.hlgt_concept_name,'NA') + '||' + isNull(concept_hierarchy.hlt_concept_name, 'NA') + '||' + isNull(concept_hierarchy.pt_concept_name,'NA') + '||' + isNull(concept_hierarchy.snomed_concept_name,'NA') concept_path, 
	ar1.count_value as num_persons, 
	ROUND(1.0*ar1.count_value / denom.count_value,5) as percent_persons,
	ROUND(ar2.avg_value,5) as length_of_era
from (select * from ohdsi.dbo.ACHILLES_results where analysis_id = 1000) ar1
	inner join
	(select stratum_1, avg_value from ohdsi.dbo.ACHILLES_results_dist where analysis_id = 1007) ar2
	on ar1.stratum_1 = ar2.stratum_1
	inner join
  (
		select snomed.concept_id, 
			snomed.concept_name as snomed_concept_name,
			pt_to_hlt.pt_concept_name,
			hlt_to_hlgt.hlt_concept_name,
			hlgt_to_soc.hlgt_concept_name,
			soc.concept_name as soc_concept_name
		from	
		(
			select concept_id, concept_name
			from CDMV5.dbo.concept
			where domain_id = 'Condition'
		) snomed
		left join
			(select c1.concept_id as snomed_concept_id, max(c2.concept_id) as pt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.domain_id = 'Condition'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id
			) snomed_to_pt
		on snomed.concept_id = snomed_to_pt.snomed_concept_id

		left join
			(select c1.concept_id as pt_concept_id, c1.concept_name as pt_concept_name, max(c2.concept_id) as hlt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) pt_to_hlt
		on snomed_to_pt.pt_concept_id = pt_to_hlt.pt_concept_id

		left join
			(select c1.concept_id as hlt_concept_id, c1.concept_name as hlt_concept_name, max(c2.concept_id) as hlgt_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) hlt_to_hlgt
		on pt_to_hlt.hlt_concept_id = hlt_to_hlgt.hlt_concept_id

		left join
			(select c1.concept_id as hlgt_concept_id, c1.concept_name as hlgt_concept_name, max(c2.concept_id) as soc_concept_id
			from
			CDMV5.dbo.concept c1
			inner join 
			CDMV5.dbo.concept_ancestor ca1
			on c1.concept_id = ca1.descendant_concept_id
			and c1.vocabulary_id = 'MedDRA'
			and ca1.min_levels_of_separation = 1
			inner join 
			CDMV5.dbo.concept c2
			on ca1.ancestor_concept_id = c2.concept_id
			and c2.vocabulary_id = 'MedDRA'
			group by c1.concept_id, c1.concept_name
			) hlgt_to_soc
		on hlt_to_hlgt.hlgt_concept_id = hlgt_to_soc.hlgt_concept_id

		left join CDMV5.dbo.concept soc
		 on hlgt_to_soc.soc_concept_id = soc.concept_id



	) concept_hierarchy
	on ar1.stratum_1 = CAST(concept_hierarchy.concept_id as VARCHAR)
	,
	(select count_value from ohdsi.dbo.ACHILLES_results where analysis_id = 1) denom
order by ar1.count_value desc

```

-------------------------------------

```
select 	concept_hierarchy.concept_id,
	isNull(concept_hierarchy.level3_concept_name,'NA') 
	+ '||' + isNull(concept_hierarchy.level2_concept_name,'NA')
	+ '||' + isNull(concept_hierarchy.level1_concept_name,'NA')
	+ '||' + isNull(concept_hierarchy.concept_name, 'NA') as concept_path,
	ar1.count_value as num_persons, 
	1.0*ar1.count_value / denom.count_value as percent_persons,
	1.0*ar2.count_value / ar1.count_value as records_per_person
from (select * from ohdsi.dbo.ACHILLES_results where analysis_id = 1800) ar1
	inner join
	(select * from ohdsi.dbo.ACHILLES_results where analysis_id = 1801) ar2
	on ar1.stratum_1 = ar2.stratum_1
	inner join
	(
		select m.concept_id, m.concept_name, max(c1.concept_name) as level1_concept_name, max(c2.concept_name) as level2_concept_name, max(c3.concept_name) as level3_concept_name
		from
		(
		select distinct concept_id, concept_name
		from CDMV5.dbo.concept c
		join CDMV5.dbo.measurement m on c.concept_id = m.measurement_concept_id
		) m left join CDMV5.dbo.concept_ancestor ca1 on m.concept_id = ca1.DESCENDANT_CONCEPT_ID and ca1.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c1 on ca1.ANCESTOR_CONCEPT_ID = c1.concept_id
		left join CDMV5.dbo.concept_ancestor ca2 on c1.concept_id = ca2.DESCENDANT_CONCEPT_ID and ca2.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c2 on ca2.ANCESTOR_CONCEPT_ID = c2.concept_id
		left join CDMV5.dbo.concept_ancestor ca3 on c2.concept_id = ca3.DESCENDANT_CONCEPT_ID and ca3.min_levels_of_separation = 1
		left join CDMV5.dbo.concept c3 on ca3.ANCESTOR_CONCEPT_ID = c3.concept_id
		group by m.concept_id, m.concept_name
	) concept_hierarchy on ar1.stratum_1 = CAST(concept_hierarchy.concept_id as VARCHAR),
	(select count_value from ohdsi.dbo.ACHILLES_results where analysis_id = 1) denom
order by ar1.count_value desc
```

---------------------------------

**Comment by chrisknoll** [comment]
@leeevans , I made the next batch of changes, but the build still hangs.  Can you find the next bottlenecks?

Also, can you confirm that my latest changes are having an effect?

**Comment by t-abdul-basser** [comment]
@chrisknoll @leeevans Thanks for chasing down these cast-related performance issues!

**Comment by chrisknoll** [comment]
@leeevans , I've removed every possible CAST to concept_id I could find (under the v5 branch).  the tests are still timing out.  On my local env, it finishes everything in 2.65 mins (pointing to the jenkins sql server.  I don't know what output testthat is waiting for, but I'm out of ideas.

**Comment by leeevans** [comment]
@chrisknoll  I believe your CAST changes have solved the issue with the slow SQL Server tests in the build job.  

However there are still two other issues with the build.

1)  I noticed that the travis build has this error message where it is trying to connect to a non-existent "yourserver" server:

```
Connecting using SQL Server driver using Windows integrated security
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host yourserver, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
```

After a lot of digging I found that this is because the R check command is incorrectly trying to execute the example R code added in this pull request:

https://github.com/OHDSI/Achilles/pull/141

The fix is to change the examples code section in https://github.com/OHDSI/Achilles/blob/export-casting-fix/man/addDatasource.Rd to wrap the example code in a "\dontrun{}" block.

i.e. The end of that file should look like this:

`\examples{
\dontrun{
jsonOutputPath <- "your/output/path"
connectionDetails <- createConnectionDetails(dbms="sql server", server="yourserver")
exportToJson(connectionDetails, cdmDatabaseSchema="cdm5", outputPath=jsonOutputPath)
addDatasource(jsonOutputPath, "your_data_name")
}
}

I would appreciate it if you could go ahead and make the above code change.

2) The other issue is that the build job also executes tests on Postgres and Oracle which are still slow.  The Postgres test takes over 10 minutes.  If you can make the above code fix I will investigate options to speed up the postgres/oracle tests, including moving those databases to a larger AWS server.

**Comment by leeevans** [comment]
@chrisknoll 

Reviewing the audit trail of closed github pull requests I found that this is the pull request where the slow build was first encountered:

https://github.com/OHDSI/Achilles/pull/119

The additional Achilles functionality added in this pull request seems to be the original root cause of the slow build issue.

One option to explore would be to try creating a branch based off of the build immediately prior to PR 119 and if that builds OK then apply and review the subsequent pull requests one at a time to see what achilles code change(s) are causing the slow tests in the build. Note The code fix for https://github.com/OHDSI/Achilles/pull/141 would need to be applied to the build prior to PR 119 first (see my previous comment).

**Comment by vojtechhuser** [comment]
PR119 only modified AchillesHeel_v5.sql file.  We can easily try it with an old Heel file and see if it fixes it. I would expect the Heel file is not the main problem.

**Comment by chrisknoll** [comment]
I've added the dontrun{} around addDatasource.  As far as that PR119, I don't think that's really where the build problems began, I think it's where the build problems were noticed.  I remember other issues where there was an open lock on a table and the first step of Achilles() was to drop the results table if it existed, and resulted in a deadlock (which timed out after the 10m).  Do you know which part of Postgresql is slow?  Or if we have similar indexes set up on postgresql?  I also seem to recall some headache with the oracle instance as well.

The Postgresql and Oracle are more of 'second languages' to me compared to sql; I don't know what sort of tuning advising you get out of the box in those platforms to help identify bottlenecks.  But if increasing the box that these environments are running on solves it (and we can afford the expense) I think that's one way to go, but I worry that we're not seeing the real issue.

**Comment by chrisknoll** [comment]
@leeevans , I've also split the testing into separate files (achilles vs. export and one file for each platform, for a total of 6 files).  I also found that we can apply a filter to the tests to only run certain tests, and so I'm going to let this one go through to see if it even gets past postgresql, and then apply a filter to only excute tests that end in _mssql.

**Comment by chrisknoll** [comment]
@leeevans , I also thing I'm noticing somethign about the 2 pending checks above after i do a push. In this case i see 2 checks happening (/travic-ci/pr and /travis-ci/push). The links for these are:
/pr: https://travis-ci.org/OHDSI/Achilles/builds/176749642
/push: https://travis-ci.org/OHDSI/Achilles/builds/176749620

This looks like 2 different builds, but the're doing nearly exactly the same thing except for what they are checking out:
/pr: 
````
$ cd OHDSI/Achilles
0.65s$ git fetch origin +refs/pull/157/merge:
remote: Counting objects: 162, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 162 (delta 124), reused 145 (delta 111), pack-reused 0
Receiving objects: 100% (162/162), 17.40 KiB | 0 bytes/s, done.
Resolving deltas: 100% (124/124), completed with 34 local objects.
From https://github.com/OHDSI/Achilles
 * branch            refs/pull/157/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
````

/push:
````
 git clone --depth=50 --branch=export-casting-fix https://github.com/OHDSI/Achilles.git OHDSI/Achilles
Cloning into 'OHDSI/Achilles'...
remote: Counting objects: 869, done.
remote: Compressing objects: 100% (432/432), done.
remote: Total 869 (delta 561), reused 659 (delta 398), pack-reused 0
Receiving objects: 100% (869/869), 418.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (561/561), done.
Checking connectivity... done.
$ cd OHDSI/Achilles
$ git checkout -qf 3797f377b099f6da79a2a3567b892adf19e52ccc
````

So i think they are each getting their own copy of the repo just one from the branch and one from a specific commit

Then, they both try to start up and execute testthat.r.  I think this is **bad** because if you have different processes trying to run achilles on the same datasource, they are going to run into each other by trying to drop tables that the other is trying to create.  This could lead to a deadlock.;

Can you please confirm that the travis jobs executed as part of respoinding to a commit isn't actually kicking off 2 jobs?

**Comment by chrisknoll** [comment]
Ok, so some good news: I if I run the two travis jobs separately and non-concurrently, the builds finish.

I spoke with @leeevans  offline, and I realize i'm not talking to the right people. @leeevans maintains our jenkins jobs (coincidentally the validation DB is on one of the jenkins servers) and I believe @msuchard and @schuemie set up the travis jobs. So I've been poking the wrong bear.

@schuemie , @msuchard : we need your help in how this travis job was set up. It seems that the 2 checks above are running the same batch of tests concurrently against the same database causing problems (for example, achilles wants to drop and create tables so having that stuff run at the same time probably is not what we want).  Since you guys hold the keys, could you please look at what's happening in this environment?  We don't think this is a database platform problem anymore.  We think it's just competing travis tasks.

**Comment by t-abdul-basser** [comment]
@chrisknoll So it looks like the CI build associated with the PR `pr` and the push to _master_ `push` completed successfully.

**Comment by chrisknoll** [comment]
Ok, just spoke with @msuchard about the travis configuration.  Here's the reason for the way it's set up today:

Travis wants to kick off the same job (build the env and execute the tests) for any push and PR trigger.  You'd want this because if someone forks the repo and opens a PR, we want the travis tests to execute. However, this leads to problems when the PR came fromt he OHDSI repo (the push and PR will happen together).  Therefore, the change I believe @msuchard  is going to look at is that the PR trigger should only fire the tests if the PR is not from the OHDSI repo.  So in this PR's case, what we'd see in the above is the /pr task would be skipped, and the /push task would do the work.  

In the case of an external fork that opens a PR, you'd only see a /pr travis task which is the case in #151.  Only the PR task is executed.

@msuchard , I'm looking closer at the travis log from #151 and it looks like we're not seeing the exports happening in that build log:
https://travis-ci.org/OHDSI/Achilles/builds/173999526#L1397

it's missing this content at the top of the log (this is from this PR's build log):
````
Setting environment variables from repository settings
$ export CDM5_POSTGRESQL_USER=[secure]
$ export CDM5_POSTGRESQL_PASSWORD=[secure]
$ export CDM5_POSTGRESQL_SERVER=[secure]
$ export CDM5_POSTGRESQL_CDM_SCHEMA=[secure]
````

The hint here is that it's pulling it from the 'repository settings'.  Maybe we could have the TRAVIS-CI build define those exports explicitly in the task instead of reading from a repository setting because maybe forked repos don't have that?  In any case, without those exports, the tests will fail. So could we also address something in the Travis jobs where when a test is going to execute, that the set of necessary travis-ci env vars are exported?

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll. This is helpful.

**Comment by msuchard** [comment]
- [x] Have updated Travis-CI so that it no longer allows concurrent builds
- [ ] Need to figure out environmental variable issues TODO

**Comment by chrisknoll** [comment]
I'd recommend putting the env vars specifically for the Travis CI in a 'hidden' location that is invoked as a script and not echo'd out to the log..instead just set 'setting travis env vars' or something. Not sure if that's possible.

Alternatively, I think we talked about making it so that travisCI has it's own parameters to set in a way that people wanting to run their own tests locally can provide their own test parameters, but again, not sure how to parameterize testthat routines.

**Comment by chrisknoll** [comment]
Ok, here's the plan and this is a short term thing, not something I want to do long term:

1. Going to create a local repo branch for all the open pull requests and merge those PRs into the local repo branch 
2. Going to then wait for those tests to complete based on the local travis CI
3. Merge the branches into master if there's no problems.

**Comment by chrisknoll** [comment]
Used squash and merge and look at the pretty history :)

**Comment by vojtechhuser** [comment]
thank you for the work on Achilles this week!

**Pull request merged**
