### PR TITLE
Run on Impala (#178)

### PR DESCRIPTION
**Pull request by chrisknoll**
* Change 'stats' to 'statsView' as STATS is a reserved word in Impala
* Cast avg and stdev to float.
* Quote 'location' since it is a reserved word in Impala
* Cast as FLOAT
* Add README for Impala
* Concat
* Cast as VARCHAR(255)

### CODE REVIEW

**Comment by chrisknoll** [comment]
This is a repo-local PR of @tomwhite #178 PR.  Once this is verified in our environment, we can merge it into master.

**Comment by chrisknoll** [comment]
@tomwhite ,
 I'm pretty sure the location change you made will break on SQL and other dbms (surrounding table names with `).  We'll see what the CI check says, but I'm almost certain that this is going to fail.

What I'd recommend is maybe a sql translation rule where you look for '.location ' and replace it with '.`location`' OR we maybe figure out how to replace table qualifiers that are used in mssql (which you surround things with [ and ]) and we can translate those to the platform specific qualifier.

@schuemie : any thoughts on if SQL render can handle the following type of translation:

```
select * from [someSchema].[someTable]
```
into:
```
select * from `someSchema`.`someTable`
```
for impala vs.
```
select # from "someSchema"."someTable"
```
for postgresql (I think postgresql uses " to surround objects that might be reserved names.

I feel like this might be something that is beyond pattern matching and instead is just a broad-stroked pre-regex-find-replace where you find everything that is surrounded in [] and replace it with the appropriate character delimiter for the platform.

**Comment by chrisknoll** [comment]
@tomwhite : one quick comment for making changes into this PR:  please update your fork and then create a PR for any updates to this pr by making PRs on your fork that target this branch (pr-178).  This is the mechanism that we can get some corrections pulled into this repo's PR branch.

**Comment by chrisknoll** [comment]
Yes, this failed. There's a huge logfile from travis, but the error is that the run on mssql failed (and I wish I could see what error was produced from the run but I can't see the error log output from travis.

I can pull this branch locally to verify that it's the ` surrounding the location table, but I'm guessing that's what it is.  

@tomwhite: remember that to make further updates to this PR, just update your fork so tha tyo uhave this branch (pr-178) and then make your own commits to that branch in your fork. Then create a PR to have your changes put directly into this branch. Travis should pick them up after I approve your PR into this branch.

**Comment by tomwhite** [comment]
Thanks for trying this out @chrisknoll. Would it be possible to rename the `location` table?

**Comment by chrisknoll** [comment]
No, the location table is part of the CDM schema. I believe this can be handled if you use double quotes (") to suround the table names and add an impala translation rule to replace " with `.

Or if you have pull with the impala folks, suggest that they use " as a quoted identifier in queries like everyone else :)

-Chris

**Comment by tomwhite** [comment]
Hi @chrisknoll. I've reverted the change to quote 'location', and changed SqlRender to handle that case, as you suggested. See https://github.com/OHDSI/Achilles/pull/186.

I've also opened https://github.com/OHDSI/SqlRender/pull/56 for the SqlRender side.

Thanks, Tom

**Comment by chrisknoll** [comment]
Ok, the plan is i'm going to take your PR and merge it into this branch here but only after the update to SQL render has been merged in (so that this branch will see the new rules).  Stay tuned, I'll try to manage this merge as quickly as possible.

**Comment by chrisknoll** [comment]
@leeevans , we're seeing an error on travis CI build that might be related to some server side configuration:

```
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "eval sudo apt-get update -qq " failed. Retrying, 3 of 3.
```

Any thoughts?

**Comment by leeevans** [comment]
@chrisknoll I can help with any jenkins build issues, @msuchard or @schuemie would be the best contacts for Travis CI build issues

**Comment by chrisknoll** [comment]
Looks like it might have been a temporary outage, I've re-kicked the job and I believe that it's getting past this error.  Thank you for responding, @leeevans .

**Comment by chrisknoll** [comment]
Ok, Achilles master officially runs on Impala!  Tho about that DELETE FROM thing....

Thank you for your efforts, @tomwhite.

**Comment by tomwhite** [comment]
Thanks for reviewing and testing this @chrisknoll!

**Pull request merged**
