### PR TITLE
Issue 151 build timeout

### PR DESCRIPTION
**Pull request by t-abdul-basser**
@leeevans This is an attempted partial fix meant to address the build timeout issue only.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Ok, looks like travis is seeing this error in the logs:

````
> test_check("Achilles")
Connecting using PostgreSQL driver
Error in connect(dbms = connectionDetails$dbms, user = connectionDetails$user,  : 
  Error: database name not included in server string but is required for PostgreSQL. Please specify server as <host>/<database>
````

I'm not sure how the travis build env has the env variables set to point to the proper database connecton strings. @leeevans can you shed light on this?

**Comment by schuemie** [comment]
Two things:

1. I'm pretty sure the env variables are not available in builds of pull requests, only when Travis builds from the repository itself. This is what is causing the errors Chris is mentioning.

2. The timeouts are caused because running the tests takes a long time on the Jenkins database server. As far as I can see the problem is SQL Server. I can see that the PostgreSQL and Oracle instances are actually empty databases, so run very quickly, but the SQL Server one has data (1,000 persons), and especially the export to JSON is taking forever. I'm sure this is because there are no indexes on the concept_id fields in the vocab tables. @leeevans : I would recommend choosing one of these two solutions: (1) have an empty database just for syntax testing, or (2) create the [required indexes](https://github.com/OHDSI/CommonDataModel/blob/master/Sql%20Server/OMOP%20CDM%20indexes%20required%20-%20SQL%20Server.sql).

**Comment by leeevans** [comment]
Hi @schuemie 

I believe I found the root cause of the issue last week. The problem is SQL Server specific. It goes to 100% CPU in the queries that cast the concept_id to varchar in joins with num_stratum in the export to JSON function.  The fix for SQL Server is to cast the num_stratum column to integer in those joins instead.  

@chrisknoll is looking into creating a pull request for that change to make sure it doesn't negatively impact APS.

So this pull request is just a stop gap measure. The current SQL code does complete on SQL Server on the CI server but it take about 50 minutes to run (with only 1000 patients) which I assume causes the Travis job to time out ( I haven't used Travis).

**Comment by schuemie** [comment]
Thanks @leeevans, that is very helpful!

But also just to be sure, can you confirm that there are indexes on the concept_id fields? I can't see any, but then I again I may not have the rights to see them.

**Comment by leeevans** [comment]
@schuemie can you email the database connection strings you are using in the Jenkins build. I'm looking at the sqlserver CDMV5 database and I see all the indexes.  Are you using the CDMV4 database perhaps?

**Comment by schuemie** [comment]
@leeevans I'm using CDMV5.dbo on jenkins.ohdsi.org. I guess I'm just not using the right SQL syntax. I was using `select * from sys.indexes`

**Comment by leeevans** [comment]
@schuemie Good we're talking about the same database.

e.g. Try this SQL:

```
use cdmv5;
select * from sysindexes where name in ('idx_concept_concept_id','idx_condition_concept_id');
```

**Comment by leeevans** [comment]
@schuemie  if you don't see the indexes then you're right, it's probably the permissions for the database user preventing you from seeing them.

**Comment by chrisknoll** [comment]
@leeevans  
  The list of indexes that should be applied on SQL Server are found in this forum thread, someone was having the same issue with export to JSON and it was taking them 40 hrs before indexes, and these indexes brought it down to < 1 hr.  They may have applied additional indexes as well per the instructions given in this thread:
http://forums.ohdsi.org/t/incremental-achilles/1847/3

Maybe that could help.

-Chris

**Comment by vojtechhuser** [comment]
The indexes will speed up the JSON - but next time a build is made (PR made), I think the indexes will be gone again (tables get dropped and re-created during achilles() call ). I think SqlRender does not have support for index creation across databases. So the indexes will help with one build. (but I could be wrong).

**Comment by t-abdul-basser** [comment]
@vojtechhuser The indexes that are being discussing will be on CDM tables (such as `concept`) that are not dropped/truncated by achilles, so that should not be a concern.

**Comment by leeevans** [comment]
@chrisknoll thanks for the suggestion about the minimum indexes in the forum thread.  The thread refers to these indexes:

https://raw.githubusercontent.com/OHDSI/CommonDataModel/master/Sql%20Server/OMOP%20CDM%20indexes%20required%20-%20SQL%20Server.sql

I double-checked the CI server sql server database and those indexes already exist. FYI @schuemie was  using a db account that didn't have access to see them.

I believe that forum thread was about speeding up the achilles function that generates the stats whereas this issue is about speeding up the achilles export to json function.

FYI. @vojtechhuser the above indexes suggested by Chris are on the cdm and vocab tables so they don't get dropped and recreated when achilles is run.

@chrisknoll I do think the answer to this slow export to json function issue on SQL Server is to switch those cast statements on the joins to concept_id.

**Comment by t-abdul-basser** [comment]
@leeevans @chrisknoll For what it is worth, our experience here at Columbia DBMI has been that there is significant overlap between the indexes that reduce Achilles results ('stats) generation (`achilles()`) and Achilles export to JSON (`exportToJSON`).

**Comment by vojtechhuser** [comment]
We are planing to eliminate the JSON export in the long run anyway. To enable some progress - I suggest we comment out the exportToJSON() call from the current R test at least this way we can test achilles() and implement new features. @t-abdul-basser  @chrisknoll

**Comment by t-abdul-basser** [comment]
@vojtechhuser I understand where you are coming from and sympathize :)  However, since I was strictly speaking are not going to eliminate the export to JSON feature (the plan is keep it not only for backward compatibility but as a (non-preferred) alternative use case) I expect to keep the code. Therefore it should be unit tested. Furthermore it still no clear to me that the timeout issue is the only issue with the builds. My goal here is to have a clean build so that we can continue to build out the great features that you guys have proposed as robust code.

**Comment by t-abdul-basser** [comment]
I would like to *withdraw/close* this PR since 1) it is my expectation is that we will come out of the effort to repair the CI tests with a much reduced execution time.

**Comment by chrisknoll** [comment]
Fine with me, I'm still working out the remaining issues on the CASTing PR. There's many more places to fix than I originally thought.  You might want to leave this open just to see what will happen.

**Comment by t-abdul-basser** [comment]
@chrisknoll Thanks. The CI/build/test timeout and CASTing issues each have their own separate issues at this point. I was just referring to the introduction of `travis_wait(90)` in the relevant commit in this PR. However, I will leave it open and modify it as necessary when we are closer to resolution with the other issues.

**Comment by t-abdul-basser** [comment]
Closing this PR as made unnecessary by #157.

**Comment by chrisknoll** [comment]
@t-abdul-basser , I think we need to use this travis_wait option that you applied, and I'm going to apply it in the open PR to see if that helps our issue.

**Comment by t-abdul-basser** [comment]
@chrisknoll That's fine. I deleted associated branch but feel free to apply and let me know if it works in the test environment.

**Pull request closed without merging**
