### PR TITLE
Closes #615

### LINKED ISSUE #615: Add number of records by drug_type_concept_Id
It would be really nice to have a report that calculates number of drug records by drug_type_concept_id

### PR DESCRIPTION
**Pull request by AnthonyMolinaro**
Successfully tested against CDM v5.4 on redshift:

```r
# Execute new analysis 707
Achilles::achilles(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  outputFolder = "D:/sandbox/Achilles",
  analysisIds = c(707),
  updateGivenAnalysesOnly = T,
  createTable = F)

# To verify
# select * from achilles_results where analysis_id = 707;
```

### CODE REVIEW

**Comment by fdefalco** [comment]
Does this stratification get exported?

**Comment by AnthonyMolinaro** [comment]
> Does this stratification get exported?

No, and if I would've looked more closely when updating the details.csv file, I would've seen we don't need this new analysis in the first place.  I should've pointed out the following to Clair before just jumping on it: [analysis 705](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/705.sql) and corresponding [export](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/export/drug/sqlDrugsByType.sql).
Given analysis 705, I don't think it makes sense to add 707.

**Comment by fdefalco** [comment]
Perhaps she is looking for an overall drug level summary report, which the data does exist for given the analysis 707, but the summary at the overall level does not exist in a report in the downstream apps.  Will clarify with @clairblacketer

**Comment by fdefalco** [comment]
resolved in https://github.com/OHDSI/Achilles/commit/edbf6abbeac5ff8f087d21dd794952c63102bbdc

**Pull request closed without merging**
