### PR TITLE
(2nd PR) Multi-threading, SQL optimizations, cost support, schema validation, logging

### PR DESCRIPTION
**Pull request by alondhe**
Fixes issues #252 , #260 #258, #210.

**This PR will require some considerable review**

1. Instead of 1 long script for Achilles and Achilles Heel, all queries are split into their own SQL files, named by an identifier defined in CSV files.
2. CTASs are used exclusively to support MPP architectures
3. v4 support is completely dropped
4. Cost analyses for the v5.1+ cost table are now supported (although they can take a long time for larger databases).
5. More appropriate hash keys are now embedded as hints in every query
6. Logging of execution times into a local RDS file. This can help us identify Achilles analyses that require optimization.
7. Wraps certain queries into inner selects in order to resolve invalid column errors found in some of our database platforms
8. Removes check of metadata table, as can be handled in the validateSchema function

### CODE REVIEW

**Comment by vojtechhuser** [comment]
A highly expected update. Thank you for working on improving Achilles.

**Comment by vojtechhuser** [comment]
The code is in your github. Can you make a branch in this repo and run the usual TravisCI step. Knowing that it passes tests would be good for final merging.

**Comment by t-abdul-basser** [comment]
@vojtechhuser Just want to confirm that we will follow the established process, i.e. 

1. review
2. test locally (as feasible)
3. merge to a named branch on origin (multithreaded_plus) and 
4. (assuming that it passes Travis CI tests) merge to master. 

One challenge for me is that I do not have a MPP DB system readily available for local testing.

**Comment by alondhe** [comment]
I'll shift the code over to the multithreaded branch later today and firm up the Travis tests. That should work against all of the Travis database platforms except Redshift and PDW. @t-abdul-basser - no need for an MPP to test this, you could test against a traditional RDBMS.

**Comment by alondhe** [comment]
Also, should I squash all of my tiny commits into one?

**Comment by t-abdul-basser** [comment]
@alondhe squash: yes.

**Comment by t-abdul-basser** [comment]
@alondhe 

Shifting: I already created the _multithreaded-plus_ branch and modified this PR (#262) to target the new branch, so I do not think that there is a need for shift your code. Reviewing the tests and adding or modifying to cover new functionality would be great. 

MPP: Understood. Thanks.

**Comment by gowthamrao** [comment]
Why is the conditional small count being removed. 

https://github.com/OHDSI/Achilles/pull/262/commits/574a9530ef9b27a5750abab2093b097c3be61470

small counts are important for rare outcomes and rare events. Why make removal mandatory? Why not keep it optional?

**Comment by alondhe** [comment]
@gowthamrao -- good catch, that was not intentional. I will bring the conditional logic back.

**Comment by alondhe** [comment]
Hi all -- I've pushed the changes as 1 commit to this branch: https://github.com/OHDSI/Achilles/tree/multithreaded-plus. It has new tests (not likely to work on all platforms due to Travis not having access to them all). And I brought back the conditional for smallCellCount as per @gowthamrao's request.

**Comment by vojtechhuser** [comment]
Travis shows error with OHDSIR TOols package

https://travis-ci.org/OHDSI/Achilles/

**Comment by vojtechhuser** [comment]
hmm. it does not even use the OHDSIRTools package. It is a generic TravisCI issue @chrisknoll

**Comment by chrisknoll** [comment]
Sorry, no idea about how that's configured.

**Comment by alondhe** [comment]
It does use OhdsiRTools for the multi-threading (cluserApply). I have it in depends, how should I implement it to force Travis to install it?

**Comment by alondhe** [comment]
@vojtechhuser I added a new commit to the branch to check for OhdsiRTools installation, and install it if needed.

**Comment by vojtechhuser** [comment]
I tried the .travis config gile today (added one entry) and the test seems to be progressing behind the prior error spot

**Comment by vojtechhuser** [comment]
extra [secure] in code

https://travis-ci.org/OHDSI/Achilles/jobs/368711264#L3046

**Comment by alondhe** [comment]
Hmm, looks like the postgres instance used by Travis doesn't have a cohort table created in the results schema. Is this something that I should add to Achilles, the creation of the table?

**Comment by t-abdul-basser** [comment]
Is cohort table needed by Achilles in this PR?

**Comment by alondhe** [comment]
@t-abdul-basser it's for analyses 1700 and 1701 (which are from the existing master branch). I can add a check for the cohort table in the results schema, and then have it create the table. Or just have the analysis skip 1700 and 1701 if the table isn't present.

**Comment by alondhe** [comment]
@vojtechhuser I pushed a new commit to the multithreaded-plus branch, which fixes the missing is_installed function and handles the case where the cohort table is not present. I also removed the older travis tests in favor of tests that are parameterized for our DB dialects. Can you help initiate a new Travis test?

**Comment by vojtechhuser** [comment]
new travicCI always triggers whenever new commit to a branch is made. I will check the result. You can do that too. simply go to travis URL for Achilles

**Comment by vojtechhuser** [comment]
https://travis-ci.org/OHDSI/Achilles/builds

image


the error seems to be 'no matching test file in dir'
https://travis-ci.org/OHDSI/Achilles/builds/371272844#L1435

**Comment by vojtechhuser** [comment]
I now see that [secure] is added by TravisCI. your solution to skip testing it if COHORT is not present make sense. Other option is to add it to the DDLs on which Achilles is being tested. The first approach is probably easier.

**Comment by t-abdul-basser** [comment]
Still reviewing, particularly in light of #268, #269 and #271. Estimated time of completion is late next week.

**Comment by vojtechhuser** [comment]
@alondhe Any updates? Light at the and of the tunnel?

**Comment by t-abdul-basser** [comment]
@vojtechhuser Sorry for delay. I expected to finish my local testing in a few hours and then merge to target branch. We will need to discuss ramifications of merging into master later, as part of release 1.6 planning.

**Comment by t-abdul-basser** [comment]
Preparing to merge manually.

**Comment by vojtechhuser** [comment]
any updates after Monday meeting?

**Comment by t-abdul-basser** [comment]
@vojtechhuser @alondhe and are meeting today to go over the branch.

**Pull request merged**
