### PR TITLE
added possibility to cache person count and descendant person count

### LINKED ISSUE #591: Add ability to cache information about person count and descendant person count

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes #591

### CODE REVIEW

**Review by alondhe — APPROVED** [review]

**Comment by alondhe** [comment]
@fdefalco and @AnthonyMolinaro -- this was functionality we asked Odysseus to add for use in Atlas (hopefully v2.10). We've tested in our environment, and it works correctly. Can you take a look?

**Comment by fdefalco** [comment]
The intent of this update is to add an option for Achilles to generate an additional table with a calculation that is then cached by WebAPI?  Is the option in WebAPI dependent on this existing?

**Comment by alondhe** [comment]
It adds columns to the existing Achilles produced table, achilles_result_concept_count. The new functionality we've added in Atlas can work without it, but it'll have to make a slower trip to the CDM to pull these person counts. With these records added to the achilles_result_concept_count table, the cache data source option can take these and make the PCs/DPCs quick.

col_name | data_type
-- | --
concept_id | string
record_count | bigint
descendant_record_count | bigint
person_count | bigint
descendant_person_count | bigint

**Comment by alondhe** [comment]
@fdefalco  -- poking the bear :) Thoughts on this PR? It complements the optional feature of PC/DPC values in Atlas 2.10.

**Comment by fdefalco** [comment]
@alondhe Are you still going to pursue this?

**Pull request closed without merging**
