### PR TITLE
additional density derived measures

### PR DESCRIPTION
**Pull request by vojtechhuser**

### CODE REVIEW

**Comment by vojtechhuser** [comment]
ignore (it was my bad click)

**Comment by t-abdul-basser** [comment]
+1

**Comment by chrisknoll** [comment]
Heh, what are we +1ing here, @t-abdul-basser ? :)

**Comment by t-abdul-basser** [comment]
I appreciating @vojtechhuser's commits, particularly the comments for additional derived measures :)

**Pull request closed without merging**
