### PR TITLE
Netezza fails with query having join without INNER, CROSS, FULL or LEFT

### PR DESCRIPTION
**Pull request by wivern**
for #251

### CODE REVIEW

**Comment by pavgra** [comment]
Guys, although this PR fixes the issue and preserves original logic, I would like to reactor it - code behavior of INNER JOIN w/o ON condition seems to be not obvious; why not to replace it with CROSS JOIN?

**Comment by chrisknoll** [comment]
Few things:  it's an error to have a 'as X' after a subquery, I believe this resutls in an error on Oracle. 

IE:
```
join (select statistic_value as val from @results_database_schema.achilles_results_derived where measure_id like 'UnmappedData:ach_401:GlobalRowCnt') **as st**
```

Second: I believe an inner join without ON  is actually a cross join. Instead of fixing this with 'inner join' why not fix it with 'cross join'?

**Comment by pavgra** [comment]
@chrisknoll, so that was the question, that I asked - is it eligable to change the join type from logical perspective? From technical point of view, no changes in behaviour should occur, but the code will become more obvious. If it is, we will do the change

**Comment by chrisknoll** [comment]
Yeah we should make joins without ON into cross join.

**Comment by t-abdul-basser** [comment]
Thanks you @wivern @pavgra for these commits and for agreeing to refactor the JOINs in question. Thank you @chrisknoll for confirming @pavgra suggestion regarding transforming the JOINs in question to CROSS JOINs. 

@vojtechhuser and I will wait for @wivern @pavgra to finish the suggested refactoring effort beore reviewing and potentially merging.

**Comment by vojtechhuser** [comment]
with the revert of Impala changes - they will have to be re-submitted

**Comment by t-abdul-basser** [comment]
@vojtechhuser  What will have to be re-submitted?

**Comment by t-abdul-basser** [comment]
Ok. Let's discuss need for resubmitting Impala changes in the relevant issue/PR.

**Comment by vojtechhuser** [comment]
@alondhe @t-abdul-basser  I am proposing merging this PR

**Comment by t-abdul-basser** [comment]
@vojtechhuser Do you have a Netezza test bed against which to test this?

**Comment by t-abdul-basser** [comment]
@pavgra @wivern @agackovka  So this failed [Travis CI Build #355](https://travis-ci.org/OHDSI/Achilles/builds/364729386) apparently due this changeset https://github.com/OHDSI/Achilles/compare/a23abd4d42df...5caa870beedd. Reverting.

**Comment by pavgra** [comment]
@t-abdul-basser, @vojtechhuser , now the PR should pass the tests due to fixes introduced in [SqlRender](https://github.com/OHDSI/SqlRender/pull/116)

**Pull request merged**
