### PR TITLE
Impala fixes

### PR DESCRIPTION
**Pull request by wivern**
Fixes OHDSI/Achilles#335

### CODE REVIEW

**Comment by t-abdul-basser** [comment]
Switched branch target to impala-fixes branch rather than master so that once reviewed and merged, fixes can be available in OHDSI project to interested users.

**Comment by pavgra** [comment]
@t-abdul-basser , not sure whether I got the idea, could you clarify why you switched it from `master`?

**Comment by t-abdul-basser** [comment]
@pavgra A couple of reasons:
1. This needs to be tested further before merging to master. See #335.
2. Our pull request SOP call for switching to merging into a non-master branch (although we are not consistent with this).
3. Merging to non-master branch allows people who want these fixes are be able to find them while we address no. 1 above.

**Comment by pavgra** [comment]
@t-abdul-basser , sounds good - looking forward to hearing from you feedback regarding performance

**Comment by vojtechhuser** [comment]
Taha, any update on when this can be merged to master (so we have clean slate for new PRs ?)
@t-abdul-basser

**Comment by t-abdul-basser** [comment]
No update on merge to master yet. I am still looking at some related issues (see above) before merging to master.

It should have been merged to fix branch however. My apologies.

**Comment by t-abdul-basser** [comment]
Merged to feature branch `impala-fixes` 12 days ago as per above.  Merged to `master` yesterday after additional testing, as per above.

**Comment by gklebanov** [comment]
@t-abdul-basser - thank you, Taha. Great stuff

**Pull request merged**
