### PR TITLE
Observation Period look back/forward queries (OHDSI SLS)

### PR DESCRIPTION
**Pull request by AnthonyMolinaro**
- This is part of the previously discussed "self learning system" of queries we are adding to Achilles.

- The purpose of these particular queries is to inform study design and answer the following question: "Given an exposure to some event (condition, drug, etc...), what proportion of people with said exposure have N days of look back/forward in observation_period?"

- There are 14 queries, each query will result in a maximum of 14 rows per concept_id inserted into achilles_results.

- This was tested against synthea and synpuf on pdw.

Example output:

```
select analysis_id,stratum_1 concept_id,stratum_3 "look back/fwd days", round(stratum_2,3) proportion 
  from achilles_results where analysis_id in (430,431) and stratum_1 = '432595'  /* Amyloidosis */
 order by 1,cast(stratum_3 as integer);

analysis_id | concept_id | look back/fwd days | proportion
------------+------------+--------------------+-----------
        430 | 432595     | 0                  |          1
        430 | 432595     | 1                  |       0.99
        430 | 432595     | 7                  |       0.98
        430 | 432595     | 14                 |       0.98
        430 | 432595     | 21                 |       0.97
        430 | 432595     | 30                 |       0.96
        430 | 432595     | 60                 |       0.93
        430 | 432595     | 90                 |        0.9
        430 | 432595     | 120                |       0.86
        430 | 432595     | 180                |        0.8
        430 | 432595     | 365                |       0.59
        430 | 432595     | 548                |       0.39
        430 | 432595     | 730                |        0.2
        431 | 432595     | 0                  |          1
        431 | 432595     | 1                  |       0.99
        431 | 432595     | 7                  |       0.99
        431 | 432595     | 14                 |       0.98
        431 | 432595     | 21                 |       0.98
        431 | 432595     | 30                 |       0.97
        431 | 432595     | 60                 |       0.95
        431 | 432595     | 90                 |       0.93
        431 | 432595     | 120                |       0.91
        431 | 432595     | 180                |       0.86
        431 | 432595     | 365                |       0.66
        431 | 432595     | 548                |       0.46
        431 | 432595     | 730                |       0.26

```

### CODE REVIEW

**Comment by alondhe** [comment]
Hi @AnthonyMolinaro, are there plans on making this information consumable through Atlas?

**Comment by AnthonyMolinaro** [comment]
@alondhe Yes!  Discussions are commencing. :)

**Comment by alondhe** [comment]
> @alondhe Yes! Discussions are commencing. :)

Could we have those documented here, even if high level? We're trying to move towards a model in which we only add Achilles precomputations or Heel rules if there's a viable way to consume that data. Otherwise, we're saddling sites with executing additional queries that they can't actually benefit from.

**Comment by fdefalco** [comment]
Here's a mockup of what we were discussing for incorporation in ATLAS.  

image

**Comment by chrisknoll** [comment]
Many concerns with this mockup, mostly from the 'function-following-form' approach to describing how the statistics are going to be leveraged, but least of which is that a database-level statistic is going to somehow derive to a 'criteria-based' estimate. Concepts applied in a cohort definition may be used as inclusion or exclusion contexts, may look for the first or latest in a time window, etc, so I question how this information could be informative in the context of criteria.  

I'd suggest you think about applying this information in the context of something simpler such as vocabulary searching. We currently leverage some of the Achilles statistics there (RC/DRC), @schuemie  presented a mock-up which showed leveraging Achilles time series plots for concepts that would inform prevalence of a concept over time; I'd follow that example and flesh out your ideas at the 'concept' level, before trying to wedge something into cohort definitions.

**Comment by pbr6cornell** [comment]
Thanks @AnthonyMolinaro  for initiating this work and for documenting that your contribution was tested on certain data and in one environment.  And thanks also @alondhe for leading as project owner for ACHILLES and trying to drive our new recommended behaviors for contributors to document the issue or new feature request, then propose an approach to a solution, before collaborating on an implementation.  As we continue to evolve our open community development practices, it'll be useful to keep each other honest with making sure we have appropriate documentation and unit testing whenever we consider expanding our solutions.  

I think having an observation period lookback/forward distribution for each concept can be quite useful.  It is extremely common when defining cohorts that we use the first occurrence of a concept as the index event, and we apply some lookback period to build our confidence that this first occurrence can be considered an 'incident' event.  We use this strategy for 'new user drug cohorts' and 'incident outcome' cohorts.   It's also useful context to know how much follow-up time exists after a first concept occurrence, particularly when characterizing incidence of an event, conducting population-level estimation, or designing patient-level prediction studies....all of which require a specification of 'time-at-risk', which could be meaningfully informed by a distribution of follow-up time for the concepts involved in defining the target cohorts.

In terms of the units of time to look forward/back, you've looked at 1/7/14/21/30/90/120/180/365/548/730d.    It may be useful for us to try to tap the community for input about what time horizons make sense across our range of use cases.   My current thinking is that we may not necessarily need all the short-term windows, because the precision of the information won't match up to specific cohorts anyway, but we may want to consider some longer windows, like 3yr, 5yr, 10yr, because I can imagine circumstances where I may care about that.   I suppose it could be possible to parameterize the input list of time windows, but there's probably value in making it a consistent list for when we get to the point that we want to share evidence across sources.

In terms of using these statistics in ATLAS to support the design of analyses, since this evidence is at the concept-level, I would recommend we focus on aspects of ATLAS that show information at the concept-level, which would include the vocabulary search and conceptsets.  My opinion on the mock that @fdefalco shared is that it would be difficult to implement appropriately, since that one time window dropdown applies to all index events (each of which can be made up of multiple conceptsets and potentially other nested criteria).  I could imagine some hoverover that provided a trellised sparkline per concept (one column for lookback time,  one for follow-up time;  one row per concept) in the used conceptsets to give you a rough sense of how each concept plays out.  I'd be happy to brainstorm other ideas as well when we get to that stage.

**Comment by alondhe** [comment]
@AnthonyMolinaro and @fdefalco -- are we still considering this PR?

**Comment by fdefalco** [comment]
Yes, though we might want to revisit @pbr6cornell 's feedback on using different windows.  Then we would integrate the information into the display on the individual concept page to avoid overcomplicating a first release of this capability.

**Pull request closed without merging**
