### PR TITLE
Add CAST to provide Achilles run over Impala CDM

### PR DESCRIPTION
**Pull request by wivern**

### CODE REVIEW

**Comment by vojtechhuser** [comment]
I just made a forum post. I am fine with the 'group by 4' - let's see what more stricter folks say . 
http://forums.ohdsi.org/t/ideas-for-sqlrender-2/932/37

Heel SQL is getting tricky to get right for all dialects. I was just about to write more rules.

**Comment by vojtechhuser** [comment]
@t-abdul-basser  can you also review?

**Comment by vojtechhuser** [comment]
thank you for fixing the group bys.
I am voting to merge (after Travis testing). I can create a February march and merge there and trigger the testing.

**Comment by t-abdul-basser** [comment]
@vojtechhuser  Thats fine. Please create feature branch (e.g. _impala_casts_) from master and merge PR commits into that. I will merge feature branch into _master_ afterwards.

**Comment by vojtechhuser** [comment]
I meant to merge it to impala_cast. I was expecting that github will offer me a choice of target branch. Please give it 1 hour. When the deed is done, we might as well let it run the TravisCI. (I am using web interface, not command line)

**Comment by vojtechhuser** [comment]
TravisCI passed. I can revert the commit to master, test it in feature branch and (see it passed) and than commit to master.    I will remember now that via web UI - merging to non-master branch is not intuitive.

**Comment by vojtechhuser** [comment]
hmm. it seems it did not pass after all. (the travis output I looked at was the revert)
@wivern 
error on oracle
image

**Comment by vojtechhuser** [comment]
I think the measure_id can be removed since it is just a string derived from analysis_id

**Comment by chrisknoll** [comment]
This is a case where I think using a subquery will hide the expression from the column value (which is where you run into problems with certain DBMS). so:

```
select a, b, sum(c), to_char(.....) as measure_id
FROM ...
WHERE analysis_id in (...)
GROUP BY a,b,to_char(...)
````

Should be rewritten as:
````
select a, b, sum(c), measure_id
FROM (
  select a, b, c, to_char(...) as measure_id
  FROM ...
  WHERE analysis_id in (...)
) Q
GROUP BY a,b,measure_id
````

**Pull request merged**
