### PR TITLE
Extend stratum fields in Achilles analysis results table

### PR DESCRIPTION
**Pull request by c4lm**
Extend the length of the fields that store achilles analysis results. Analysis with id 1900 collects CDM source values which may be very long depending on the dataset and ETL agreements.

### CODE REVIEW

**Comment by t-abdul-basser** [comment]
Varchar(max)is typically used when the sizes of the column data entries vary considerably, and the size might exceed 8,000 bytes. Do we have a use case that supports this?

**Comment by chrisknoll** [comment]
I agree with the concerns on varchar(max).  That's for storing things > 1GB, which i'm sure a statum column does not need to be.  255 should be plenty to stratify with, and where we run into issues, we should look into trimming strategies for keeping the length reasonable.  If it is a problem with long concept names, perhaps those stratum should be stored as concept_id, and later when we query out of the table, we join to the vocabulary concept table.

**Comment by c4lm** [comment]
We have CDM source values that are longer than 255 (up to 300 characters), and we've dealt with the issue locally - there are at least three ways to fix this: 
- change Achilles tables DDL; 
- create views that would crop the source values
- disable analysis with id=1900

I agree that varchar(max) may be too long, but there is a case when people want to run full latest Achilles analysis version inside a Docker image, uchanged. 
Not having necessary database access to modify the data the analysis runs on would be an obstacle in this case; views that crop string values would increase execution time.

**Comment by chrisknoll** [comment]
I'm looking over the CDM ddl, and I don't see any soruce values that are varchar(300)?  Where are you seeing this?

For analysis 1900, I think the code should have a LEFT(source_value, 255) to truncate the value.  Or this can be handled in the ETL where a source value is mapped down to an integer ID (perhpas using distinct and row_number()) and then you store the source_value as this surrogate identifier. Of course, then the stratum contains this number and it's not clear in the report what the actual value is without joining back to the original source's mapped table (which isn't stored in the CDM). Possibly it might be worth a CDM enhancement where you have a new source_value_map table which allows you to resolve distinct source values into an identifier so that you can store any length you want in the table but reference the value by ID.  Of course, that's a bigger scope of a change.

**Comment by c4lm** [comment]
Sorry, I was being unclear.
People extend standard DDL length when they want to store source data that can't fit into the standard field length, for instance, we could have more than 2 characters for location.state, and in my particular case, more than 255 characters for measurement_source_value and observation_source_value, for example:

'ORDER_NM: LUNG CANCER SCREENING WITH LOW DOSE COMPUTED TOMOGRAPHY (CT SCAN) IN 55-80 YEARS OLD.  CURRENTLY FOR SMOKERS AT 55-80 YEARS OF AGE AND HAVE HAD MORE THAN 30 YEARS OF SMOKING MORE THAN 1 PACK PER DAY AND YOU CURRENTLY SMOKE OR HAVE QUIT WITHIN PAST 15 YEAR'

As for the idea of assigning an id to the source value: 
We have '*_source_concept_id' fields in the CDM, which could be used for that purpose in case when there is no intermediate mapping using non-standard concepts (i.e. when we map source values directly to standard concepts) - we can generate our own concepts, (like suggested [here](http://forums.ohdsi.org/t/source-to-concept-map-table/3334) and create additional, in-house concept, vocabulary and concept_relationship tables with their own vocabulary_ids and concept_ids, mapping, but unfortunately this indeed does not solve the issue since we still want to write the full source value into the CDM table field.

**Comment by chrisknoll** [comment]
I understand, if you trim off the ORDER_NM: the length goes down to 254 characters.  But I don't want to suggest that you need to slice up your data to fit it into the cdm...

So, i think varchar(max) is bad (because that gets handled different on different datasoruces and sometimes it has severe negative impacts in the storage of the data and the efficiency of querries.  varchar (500) (approx doubling the 255) would probably be fine.  But I do worry that this leads to more and more verbose values being stored in the data leading to bloat.

The ideal solution would be to expand your concept name table to be varchar(500) so you can fit your custom concepts in there, and do the in-house concept creation, and store the source concept_id in the table.  Do you really want to repeat

'ORDER_NM: LUNG CANCER SCREENING WITH LOW DOSE COMPUTED TOMOGRAPHY (CT SCAN) IN 55-80 YEARS OLD. CURRENTLY FOR SMOKERS AT 55-80 YEARS OF AGE AND HAVE HAD MORE THAN 30 YEARS OF SMOKING MORE THAN 1 PACK PER DAY AND YOU CURRENTLY SMOKE OR HAVE QUIT WITHIN PAST 15 YEAR'

in your data once per measurement (which could be millions aka. gigabytes of storage) when you can just store a bigint with the source_concept_id which would be megabytes?  That being said, I understand that every row has a source_value field but I'd expect that the Lung Cancer Screening above has some sort of procedure code associated with it and so you could store the source_value as the code of this procedure instead of the name+description.

In any case, I fully acknowledge I don't know the entire situation of your data, so please don't interpret anything I'm suggesting as you are doing anything wrong.  My job here is to balance platform capabilities with implementation details like performance and optimizations.  I sincerely hope there's a way for you to fit into the CDM because there are a lot of great capabilities that come with the platform.

**Comment by c4lm** [comment]
> The ideal solution would be to expand your concept name table to be varchar(500) so you can fit your custom concepts in there, and do the in-house concept creation, and store the source concept_id in the table.
We actually do this!
The only case where we have to insert these long strings is if we don't have a short code, but we can map the string value via huge custom mapping directly to standard concept (or if we don't have a code and the value from that string field is unmapped).

I think that the situation just implies that at the moment deviating from standard DDLs probably should be more frowned upon in the community, from the perspective of using OHDSI tools and studies that could rely on compliance to those DDLs.

**Comment by chrisknoll** [comment]
So that leaves us back to the problem you are actually having. The nice/not nice thing about the results schema (where achilles writes the results) is that it's not standardized (tho it is equally frowned upon to alter it from the 'published' tools (such as Achilles).  But a shift from varchar 255 to varchar(500) is more tenable than varchar(max) so maybe that would be more acceptable? I know it's not exactly the right direction of a solution, but I also hate seeing people left hanging.

**Comment by vojtechhuser** [comment]
I think going the "twitter" way is a good approach. from 255 to more. What is the max value in your data currently? Double would be 510.

**Pull request closed without merging**
