### PR TITLE
Added BigQuery support

### PR DESCRIPTION
**Pull request by pavgra**

### CODE REVIEW

**Comment by t-abdul-basser** [comment]
Thank you for this @pavgra.  Enhancing our BQ support is important and welcome contribution. I have started my review. Please note that we will target the next release for this. 
This PR needs to be thoroughly tested, of course. There are change to SQLRender that may need to be addressed first before this is approved. We also need to take this opportunity to add the ability to perform BigQuery testing via Travis. @alondhe and I are working with @leeevans  and @schuemie regarding this.

**Comment by pavgra** [comment]
@t-abdul-basser , required SqlRender changes have already been merged:
https://github.com/OHDSI/SqlRender/pull/150

**Comment by t-abdul-basser** [comment]
Thanks @pavgra. I finished the code review.  

@alondhe @vojtechhuser I propose that we wait to merge while we continue with our efforts to procure and stand up a OMOP test DB for Achilles testing.

**Comment by t-abdul-basser** [comment]
Will add BQ testing to CI in different PR.

**Comment by alondhe** [comment]
@pavgra -- sorry for the delay on my end. In this snippet, https://github.com/OHDSI/Achilles/blob/00b624723f2595276ace84e606540c8d402b5416/R/Achilles.R#L208-L214, we may want to have logic to set scratchDatabaseSchema to something that isn't "#" should the user pick BigQuery and have scratchDatabaseSchema  set to "#". Perhaps set it back to resultsDatabaseSchema.

**Comment by pavgra** [comment]
@alondhe , so where am I changing the logic or behavior in this case? I only surrounded part of already existing code with condition which verifies that temp tables are supported by DB before utilizing them. But the line `scratchDatabaseSchema <- "#"` existed before

**Comment by alondhe** [comment]
> @alondhe , so where am I changing the logic or behavior in this case? I only surrounded part of already existing code with condition which verifies that temp tables are supported by DB before utilizing them. But the line `scratchDatabaseSchema <- "#"` existed before

You're right, I'm just thinking of a flaw in my original code :)

**Pull request merged**
