### PR TITLE
Brought back missing analyses, bugfixes for PG/Oracle, Redshift

### PR DESCRIPTION
**Pull request by alondhe**
Fixes for #320 , #317 , #311, #307. Also, usage of DatabaseConnector::getTableNames() isn't working 100% of the time for Redshift clusters, so removed that and just remove all possible scratch tables in dropAllScratchTables().

### CODE REVIEW

**Comment by vojtechhuser** [comment]
consider changing version to something higher - e.g., 1.7 or 1.6.1

**Comment by alondhe** [comment]
@vojtechhuser -- thanks, good idea. I just incremented it to 1.6.1. Perhaps we can merge these requests first, and then bring in @pegeler's great organizational updates for 1.6.2?

**Comment by t-abdul-basser** [comment]
I am review and will merge into master @vojtechhuser. Please do not hit merge for this PR or @pegeler's :)

**Comment by t-abdul-basser** [comment]
@alondhe Yes, I agree: The changes made hereto with the addition of this PR are suitable for 1.6.1. @pegeler PR--though mostly acceptable as is--is non-trivial and needs a bit more review.

**Pull request merged**
