### PR TITLE
Added Export Domain Meta functionality

### PR DESCRIPTION
**Pull request by alondhe**
This function will allow organizations using the CDM_DOMAIN_META table in their CDMs to export this information to a JSON file that can then be served up by AchillesWeb.

### CODE REVIEW

**Comment by chrisknoll** [comment]
I agree I think this looks good, and doesn't interfere with Achilles statistic processing so this update is pretty low risk.  Adding a test case is also a good idea so if you add that I'd very much like to see how it's implemented because (blush) I haven't written any test cases and it's something I need to start doing.

**Comment by vojtechhuser** [comment]
I welcome new functionality additions.

**Comment by t-abdul-basser** [comment]
@chrisknoll :) I was thinking that it would be desirable for @alondhe and the rest of us to follow @schuemie's lead and emulate his associated test patterns that use the  [_testthat_ ](https://github.com/hadley/testthat) framework. For another good set of tests to emulate, see [ggplot tests](https://github.com/tidyverse/ggplot2/tree/master/tests/testthat). However, because 1)  I agree that it is low risk; 2) we are still squashing bugs in the build and 3) the @vojtechhuser dictum ["I welcome new functionality"], *lets approve this PR*. I will merge it.

**Comment by chrisknoll** [comment]
Ok, I agree fully @t-abdul-basser .

One comment on how this merge was done: can you use the 'squash and merge' option it will do 2 things:  collapse all commits down to a single commit (which is N/A in this case since it's a single commit) but it also will not have an empty 'merge commit' node on the git history, rather it'll look like the PR was just a commit that came into the tip of the master branch (which looks cleaner).  Thanks!

**Comment by t-abdul-basser** [comment]
@chrisknoll Yes. Squash and ,erge is on checklist but I ignored it as PR consisted on one commit. You make a good point concerning the history entry though. I will keep in mind Thanks!

**Pull request merged**
