### PR TITLE
Fix for #309: Oracle error on selecting null values

### LINKED ISSUE #309: ORACLE Error ORA-01723: zero-length columns are not allowed
### Expected behavior
successful running 'achilles' command on Achilles 1.6.0 (master)
with oracle database
```
DBMS:
oracle

Error:
java.sql.SQLSyntaxErrorException: ORA-01723:  zero-length columns are not allowed


SQL:
--HINT DISTRIBUTE_ON_KEY(stratum_1)
CREATE TABLE ckwnf8oys_tmpach_0
 AS
SELECT
0 as analysis_id,  CAST('My Source Name' AS VARCHAR(255)) as stratum_1, CAST('1.6' AS VARCHAR(255)) as stratum_2, 
CAST(SYSDATE AS VARCHAR(255)) as stratum_3,
null as stratum_4, null as stratum_5,
COUNT(distinct person_id) as count_value

FROM
CDM.PERSON 

R version:
R version 3.5.1 (2018-07-02)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.6)
- OhdsiRTools (1.5.5)
- httr (1.3.1)
- openxlsx (4.1.0)
- rjson (0.2.20)
- DatabaseConnector (2.1.4)
- SqlRender (1.5.2)
- devtools (1.13.6)
```
### Actual behavior
run 'achilles' failed
### Steps to reproduce behavior
1. use oracle database
2. run achilles(connectionDetails, cdmDatabaseSchema = ...)

### PR DESCRIPTION
**Pull request by alondhe**
This fixes #309 by casting all CTAS nulls to the field types of the fields they will eventually fill.

### CODE REVIEW

**Comment by vojtechhuser** [comment]
can we add the missing measures too pls 1822

**Comment by vojtechhuser** [comment]
here is the code for it


--{823 IN (@list_of_analysis_ids)}?{
-- 823	Number of observation records, by observation_concept_id and qualifier_concept_id
INSERT INTO @results_database_schema.ACHILLES_results (analysis_id, stratum_1, stratum_2, count_value)
SELECT 
	823 AS analysis_id, 
	CAST(observation_concept_id AS VARCHAR(255)) AS stratum1_id, 
	CAST(qualifier_concept_id AS VARCHAR(255)) AS stratum2_id,
	COUNT_BIG(*) AS count_value
FROM @cdm_database_schema.observation
GROUP BY observation_concept_id, qualifier_concept_id
;
--}


--{823 IN (@list_of_analysis_ids)}?{
-- 823	Number of observation records, by observation_concept_id and qualifier_concept_id
INSERT INTO @results_database_schema.ACHILLES_results (analysis_id, stratum_1, stratum_2, count_value)
SELECT 
	823 AS analysis_id, 
	CAST(observation_concept_id AS VARCHAR(255)) AS stratum1_id, 
	CAST(qualifier_concept_id AS VARCHAR(255)) AS stratum2_id,
	COUNT_BIG(*) AS count_value
FROM @cdm_database_schema.observation
GROUP BY observation_concept_id, qualifier_concept_id
;
--}



1822,"Number of measurement records, by measurement_concept_id and value_as_concept_id","measurement_concept_id","value_as_concept_id",,,
1823,"Number of measurement records, by measurement_concept_id and operator_concept_id","measurement_concept_id","operator_concept_id",,,
822,"Number of observation records, by observation_concept_id and value_as_concept_id","observation_concept_id","value_as_concept_id",,,
823,"Number of observation records, by observation_concept_id and qualifier_concept_id","observation_concept_id","qualifier_concept_id",,,



--{1822 IN (@list_of_analysis_ids)}?{
-- 1822	Number of measurement records, by measurement_concept_id and value_as_concept_id
INSERT INTO @results_database_schema.ACHILLES_results (analysis_id, stratum_1, stratum_2, count_value)
SELECT
	1822 AS analysis_id,
	CAST(measurement_concept_id AS VARCHAR(255)) AS stratum1_id,
	CAST(value_as_concept_id AS VARCHAR(255)) AS stratum2_id,
	COUNT_BIG(*) AS total_count
FROM @cdm_database_schema.measurement
GROUP BY measurement_concept_id, value_as_concept_id;
--}

--{1822 IN (@list_of_analysis_ids)}?{
-- 1822	Number of measurement records, by measurement_concept_id and value_as_concept_id
INSERT INTO @results_database_schema.ACHILLES_results (analysis_id, stratum_1, stratum_2, count_value)
SELECT
	1822 AS analysis_id,
	CAST(measurement_concept_id AS VARCHAR(255)) AS stratum1_id,
	CAST(value_as_concept_id AS VARCHAR(255)) AS stratum2_id,
	COUNT_BIG(*) AS total_count
FROM @cdm_database_schema.measurement
GROUP BY measurement_concept_id, value_as_concept_id;
--}

**Comment by alondhe** [comment]
One lesson from 1.6: don't try to fit in too many changes in 1 push. I'll add this into a separate PR.

**Comment by mgweiner** [comment]
The fix to Issue 309 addressed the zero-length column issue in the various SQL files within the Achilles\sql\sql_server\analyses directory.

Unfortunately, there are additional sql statements with a similar problem within the

Achilles\sql\sql_server\post_processing\concept_hierarchy.sql file

and all the files in the
Achilles\sql\sql_server\post_processing\concept_hierarchies directory

**Pull request merged**
