### PR TITLE
R code changes (.dbo removal), addition of rule 29, minor changes to rule 28, CSV overview updates.

### PR DESCRIPTION
**Pull request by vojtechhuser**
removing .dbo parts of the code (resultsDatabase and other old similar variables)
adding rule 29 (pediatric diagnosis detected at senior age)
rule28 changed to notification from warning
documentation updates (CSV files for analyses overview)

It works on IMEDS RedShift and Lee's MS SQL Server.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Hi, @vojtechhuser ,
Could you do the following:
1. Please name this pull request to a title that reflects its purpose.
2. Can you confirm that this executes on MSSQL.  The call to USE @resultsdatabaseschema doesn't feel like it would work if you set the resultsdatabaseschema to soemthing like "DATABASENAME.dbo"

I am pretty sure we no longer need to use the USE XXXX commands in sql since any table we reference should be fully qualified with the table qualifier.

I made a comment about this in this forum post: http://forums.ohdsi.org/t/getting-rid-of-dbo-in-our-parameterized-sql/267/14

Unless you heard something different from @schuemie , we shoudln't need any of the database properties at all (including calls to USE).

-Chris

**Comment by vojtechhuser** [comment]
Please see my email.

The use statement has been removed. 
the current code works OK   on Redshift and sql server

**Comment by chrisknoll** [comment]
This was merged and conflicts resolved manually.
@vojtechhuser , I think the resulting commits that were merged into master are not identical to the ones in your branch, so you will want to delete your own branch and then create new branches off of master for future development work.

**Comment by chrisknoll** [comment]
I've cleaned up the branch on the server (after confirming your commits were merged into master). You should delete your own local branch of devH.  For future development, pull latest master branch, and create new development branches off master.

**Pull request closed without merging**
