### PR TITLE
CASTs for Impala

### PR DESCRIPTION
**Pull request by wivern**
for #245

### CODE REVIEW

**Comment by vojtechhuser** [comment]
current vignete does not describe the "gotcha"
https://github.com/OHDSI/SqlRender/issues/111

**Comment by vojtechhuser** [comment]
we can merge only after the group by problem is addressed.

**Comment by t-abdul-basser** [comment]
@pavgra @wivern Given https://github.com/OHDSI/Achilles/pull/252 do you still want to submit this?

**Comment by pavgra** [comment]
@t-abdul-basser, @vojtechhuser, yes, we'd like to have this merged. The issue with group by and all conflicts were resolved

**Comment by t-abdul-basser** [comment]
Yes. Should be merged within the hour. Thanks.

**Pull request merged**
