### PR TITLE
fixed the end of year with December 31 23:59:59

### PR DESCRIPTION
**Pull request by Andreyyiv**
solves https://github.com/OHDSI/Achilles/issues/473

### CODE REVIEW

**Comment by alondhe** [comment]
@Andreyyiv I think BigQuery doesn't yet have a datetimefromparts translation pattern. Can you first confirm that all supported dialects do?

**Comment by Andreyyiv** [comment]
@alondhe  The current [replacement patterns](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv) contain `DATETIMEFROMPARTS` only for the following dialects: oracle, postgresql, redshift, netezza, sqlite. These are not covered: pdw, impala, bigquery, hive.

**Comment by alondhe** [comment]
> @alondhe The current [replacement patterns](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv) contain `DATETIMEFROMPARTS` only for the following dialects: oracle, postgresql, redshift, netezza, sqlite. These are not covered: pdw, impala, bigquery, hive.

Hmm...we should get those patterns authored and accepted before making use of datetimefromparts in Achilles master.

**Comment by alondhe** [comment]
we should get those patterns authored and accepted before making use of datetimefromparts in Achilles master.

**Pull request closed without merging**
