### PR TITLE
Dev huser branch to master (report function)

### PR DESCRIPTION
**Pull request by vojtechhuser**
Achilles Report functionality (discussed during 1.5 hour call with Martijn and reported in the issue tracker).

### CODE REVIEW

**Comment by chrisknoll** [comment]
Vojtech,
 Could you update this pull request description with a few bullets from your 1.5h meeting that describe what is included in this PR so that others not in the meeting will be able to understand the purpose of this PR?

Thank you.

**Comment by vojtechhuser** [comment]
This PR addresses issue 72. https://github.com/OHDSI/Achilles/issues/72 
Also, this forum post describes the report functionality with some time allowed for community input.
http://forums.ohdsi.org/t/additions-to-achilles/1283/3

No existing functionality is impacted. R code has a new function  (see diff) that calls a new SQL file. 

Please comment on the naming if the table name should be changed or the column names. The SQL code has comments explaining it in few places. 

The summary of the 1.5 hour call with Martijn is in the forum post (additions to achilles) and also discussed at weekly meeting.

**Comment by chrisknoll** [comment]
Hi, Vojtech,
I’ve been reviewing it.  One comment is the introduction of the new table: Achilles_report.  My question is:   could the existing Achilles_results table be used to capture these domain-table level statistics?  The structure of the results table is:
~~~ sql
(
                analysis_id int,
                stratum_1 varchar(255),
                stratum_2 varchar(255),
                stratum_3 varchar(255),
                stratum_4 varchar(255),
                stratum_5 varchar(255),
                count_value bigint
);
~~~

If you created a new analysis ID in a new range (say 1900, because the latest range is 1800, and this 1900 range could be considered a ‘reporting’ type of statistics range) where you insert the data you’ve calculated with 1900 as the analysis ID, and stratum_1 will be set to table_name, stratum_2 is the source value, and you’d insert it like so:

~~~sql
INSERT INTO @results_database_schema.ACHILLES_RESULTS (analysis_id, stratum_1, stratum_2, count_value)
select 1900 as analysis_id, table_name, source_value, count_value 
from (
  select 'measurement' as table_name,measurement_source_value as source_value, COUNT_BIG(*) as cnt from measurement where measurement_concept_id = 0 group by measurement_source_value 
   union
 select 'procedure_occurrence' as table_name,procedure_source_value as source_value, COUNT_BIG(*) as cnt from procedure_occurrence where procedure_concept_id = 0 group by procedure_source_value 
   union
  select 'drug_exposure' as table_name,drug_source_value as source_value, COUNT_BIG(*) as cnt from drug_exposure where drug_concept_id = 0 group by drug_source_value 
   union
   select 'condition_occurrence' as table_name,condition_source_value as source_value, COUNT_BIG(*) as cnt from condition_occurrence where condition_concept_id = 0 group by condition_source_value
) Q
~~~

To produce your report you select stratum_1 as table_name, stratum_2 as source_value, count_value from ACHILLES_RESULTS where analysis_id = 1900.

You can also do group-by-count clause to roll up all tables into one count, for example.

I do understand one advantage of your report table is that the columns names are explicit, however the down side is that it’s very specific and if everyone followed this pattern, we’d end up with potentially dozens of tables that store same types of statics but with different column names.

**Comment by vojtechhuser** [comment]
a revised PR will be made

**Pull request closed without merging**
